"use strict";
const randomWord = require("random-words");
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Questions",
      [
        {
          id: 1,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 2,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 4,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          id: 5,
          name: randomWord(1),
          answer: "text",
          cost: 100,
          theme_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 6,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 8,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9,
          name: randomWord(1),
          answer: "text",
          cost: 100,
          theme_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 11,
          name: randomWord(1),
          answer: "text",
          cost: 301000,
          theme_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 12,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 13,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 14,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          id: 15,
          name: "joji",
          answer: "text",
          cost: 100,
          theme_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          id: 16,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 17,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 18,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 19,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 20,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 21,
          name: randomWord(1),
          answer: "text",
          cost: 100,
          theme_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 22,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 23,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 24,
          name: randomWord(1),
          answer: "text",
          cost: 300,
          theme_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 25,
          name: randomWord(1),
          answer: "text",
          cost: 100,
          theme_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },
};
